name: Build luci-theme-argon

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.branch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - x86_64
        branch:
          - openwrt-23.05

    steps:
      # - uses: actions/checkout@main
      #   with:
      #     fetch-depth: 0

      - name: Checkout Source Code
        run: |
          git clone --depth 1 https://github.com/jerrykuku/luci-app-argon-config
          git clone --depth 1 https://github.com/jerrykuku/luci-theme-argon

      - name: Building packages
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: packages_ci
          PACKAGES: luci-theme-argon luci-app-argon-config 
          NO_REFRESH_CHECK: true

      - name: ipks
        run: |
          cd bin/packages/
          find . -name "*.ipk"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: luci-app-argon-${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
